// src/routes/fire/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { Flame, Target, Coins, Plus, Trash2, SlidersHorizontal, Pencil, Wallet, Gem, TrendingUp, PiggyBank, ShieldCheck } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import CardHeader from "$lib/components/ui/CardHeader.svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import Field from "$lib/components/ui/Field.svelte";
  import Dialog from "$lib/components/ui/Dialog.svelte";
  import Stat from "$lib/components/ui/Stat.svelte";
  import Progress from "$lib/components/ui/Progress.svelte";
  import PageHeader from "$lib/components/ui/PageHeader.svelte";
  import Loading from "$lib/components/ui/Loading.svelte";
  import AreaChart from "$lib/components/charts/AreaChart.svelte";
  import Legend from "$lib/components/charts/Legend.svelte";
  import { t } from "$lib/i18n";
  import { prefs } from "$lib/prefs.svelte";
  import { DEFAULT_PARAMS, project, startCapital, type Assets, type FireParams } from "$lib/fire";
  import { apiJson, cn, fmtEUR, fmtEUR0, fmtNum } from "$lib/utils";

  type Scenario = { id: number; name: string; createdAt: string; params: FireParams };

  const COLORS = ["#f0652f", "#2f6fed", "#7950f2", "#12a150", "#f59f00", "#e64980"];

  let scenarios = $state<Scenario[] | null>(null);
  let assets = $state<Assets>({ cash: 0, metals: 0, investments: 0, pension: 0 });
  let emergency = $state<{ balance: number; accountName: string } | null>(null);
  let activeId = $state<number | null>(null);
  let editing = $state<Scenario | null>(null);
  let editOpen = $state(false);
  let draft = $state<FireParams>(structuredClone(DEFAULT_PARAMS));
  let draftName = $state("");
  let isNew = $state(false);
  let busy = $state(false);

  async function load() {
    const [f, s] = await Promise.all([
      apiJson<{ scenarios: Scenario[] }>("/api/fire"),
      apiJson<{ assets?: Assets; emergency?: { balance: number; accountName: string } | null }>("/api/summary"),
    ]);
    assets = s.assets ?? { cash: 0, metals: 0, investments: 0, pension: 0 };
    emergency = s.emergency ? { balance: s.emergency.balance, accountName: s.emergency.accountName } : null;
    scenarios = f.scenarios;
    activeId = activeId ?? f.scenarios[0]?.id ?? null;
  }
  onMount(load);

  function openEdit(s: Scenario) {
    editing = s;
    draft = structuredClone($state.snapshot(s.params));
    draftName = s.name;
    isNew = false;
    editOpen = true;
  }
  function openNew() {
    const base = scenarios?.find((s) => s.id === activeId)?.params ?? DEFAULT_PARAMS;
    editing = { id: -1, name: "", createdAt: "", params: base };
    draft = structuredClone($state.snapshot(base));
    draftName = "";
    isNew = true;
    editOpen = true;
  }

  async function save() {
    busy = true;
    const params = $state.snapshot(draft);
    if (isNew) {
      const res = await fetch("/api/fire", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name: draftName || t("Neues Szenario"), params }),
      });
      const d = await res.json();
      if (res.ok) activeId = d.id;
    } else if (editing) {
      await fetch("/api/fire", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: editing.id, name: draftName, params }),
      });
    }
    busy = false;
    editOpen = false;
    load();
  }

  async function remove(id: number) {
    if (!confirm(t("Szenario wirklich löschen?"))) return;
    const res = await fetch(`/api/fire?id=${id}`, { method: "DELETE" });
    if (!res.ok) { alert((await res.json()).error); return; }
    if (activeId === id) activeId = null;
    load();
  }

  const year = new Date().getFullYear();
  // Live preview in the editor
  const preview = $derived(editOpen ? project(draft, assets, year) : null);
  const projections = $derived((scenarios ?? []).map((s, i) => ({ scenario: s, p: project(s.params, assets, year), color: COLORS[i % COLORS.length] })));
  const active = $derived(projections.find((x) => x.scenario.id === activeId) ?? projections[0]);

  /** All scenarios on one age axis — each scenario is one column. */
  const chartRows = $derived.by(() => {
    const byAge = new Map<number, Record<string, number | string>>();
    for (const { scenario, p } of projections) {
      for (const pt of p.series) {
        const age = Math.round(pt.age);
        const row = byAge.get(age) ?? { age, label: t("{n} J.", { n: age }) };
        row[`s${scenario.id}`] = pt.value;
        byAge.set(age, row);
      }
    }
    return [...byAge.values()].sort((a, b) => Number(a.age) - Number(b.age));
  });

  const ASSET_ROWS = $derived<Array<{ key: keyof Assets; label: string; icon: typeof Wallet; color: string }>>([
    { key: "cash", label: t("Liquidität"), icon: Wallet, color: "#2f6fed" },
    { key: "investments", label: t("Investments"), icon: TrendingUp, color: "#7950f2" },
    { key: "metals", label: t("Edelmetalle"), icon: Gem, color: "#c49a1a" },
    { key: "pension", label: t("Altersvorsorge"), icon: PiggyBank, color: "#12a150" },
  ]);

  type NumKey = "age" | "monthlySavings" | "monthlyExpenses" | "annualReturnPct" | "inflationPct" | "withdrawalRatePct";
  const SLIDERS = $derived<Array<{ key: NumKey; label: string; min: number; max: number; step: number; fmt: (v: number) => string }>>([
    { key: "age", label: t("Aktuelles Alter"), min: 18, max: 70, step: 1, fmt: (v) => t("{n} Jahre", { n: v }) },
    { key: "monthlySavings", label: t("Sparrate / Monat"), min: 0, max: 10000, step: 50, fmt: (v) => fmtEUR0(v) },
    { key: "monthlyExpenses", label: t("Wunsch-Ausgaben im Ruhestand / Monat (heutige Kaufkraft)"), min: 500, max: 15000, step: 100, fmt: (v) => fmtEUR0(v) },
    { key: "annualReturnPct", label: t("Erwartete Rendite p. a."), min: 0, max: 12, step: 0.1, fmt: (v) => `${fmtNum(v, 1)} %` },
    { key: "inflationPct", label: t("Inflation p. a."), min: 0, max: 6, step: 0.1, fmt: (v) => `${fmtNum(v, 1)} %` },
    { key: "withdrawalRatePct", label: t("Entnahmerate (SWR)"), min: 2, max: 6, step: 0.1, fmt: (v) => `${fmtNum(v, 1)} %` },
  ]);

  const yearsLabel = (y: number | null) =>
    y === null ? t("> 60 J.") : y === 0 ? t("Erreicht 🎉") : t("{n} Jahre", { n: fmtNum(y, 1) });
  const axis = (v: number) => new Intl.NumberFormat(prefs.locale, { notation: "compact", maximumFractionDigits: 1 }).format(v);
</script>

<svelte:head><title>FIRE · Achilles</title></svelte:head>

{#if !scenarios}
  <Loading rows={2} />
{:else}
  <div class="rise space-y-6">
    <PageHeader title={t("FIRE-Simulator")} subtitle={t("Financial Independence, Retire Early — alle Werte inflationsbereinigt in heutiger Kaufkraft.")}>
      {#snippet actions()}
        <Button size="sm" onclick={openNew}><Plus /> {t("Szenario anlegen")}</Button>
      {/snippet}
    </PageHeader>

    {#if active}
      <div class="grid grid-cols-2 gap-4 xl:grid-cols-4">
        <Stat icon={Target} color="#f0652f" label={t("FIRE-Zahl")} value={fmtEUR0(active.p.fireNumber)} sub={t("bei {pct} % Entnahme", { pct: fmtNum(active.scenario.params.withdrawalRatePct, 1) })} />
        <Stat icon={Coins} color="#2f6fed" label={t("Startkapital")} value={fmtEUR0(active.p.start)} sub={active.scenario.params.startNetWorth === null ? t("aus gewählten Bausteinen") : t("manuell gesetzt")} />
        <Stat icon={Flame} color="#f59f00" label={t("Fortschritt")} value="{fmtNum(active.p.progressPct, 1)} %" sub={t("{amount} fehlen", { amount: fmtEUR0(Math.max(0, active.p.fireNumber - active.p.start)) })} />
        <Stat icon={SlidersHorizontal} color="#7950f2" label={t("Realrendite")} value="{fmtNum(active.p.realAnnualPct, 1)} %" sub={t("nach Inflation")} />
      </div>
    {/if}

    <Card>
      <CardHeader title={t("Vermögensprojektion (real)")}>
        {#snippet actions()}
          <Legend items={[...projections.map((x) => ({ label: x.scenario.name, color: x.color })), ...(active ? [{ label: t("FIRE-Zahl"), color: "var(--warn)", dashed: true }] : [])]} />
        {/snippet}
      </CardHeader>
      <div class="px-3 pb-4">
        <AreaChart
          data={chartRows}
          x="label"
          height={380}
          xTicks={8}
          yFormat={axis}
          valueFormat={fmtEUR0}
          refLine={active ? { value: active.p.fireNumber, color: "var(--warn)" } : null}
          series={projections.map((x) => ({ key: `s${x.scenario.id}`, label: x.scenario.name, color: x.color, fill: x.scenario.id === active?.scenario.id }))}
        />
      </div>
    </Card>

    <div>
      <h2 class="mb-3 text-[15px] font-semibold">{t("Szenarien")}</h2>
      <div class="grid grid-cols-1 gap-4 lg:grid-cols-2 xl:grid-cols-3">
        {#each projections as { scenario, p, color } (scenario.id)}
          {@const isActive = scenario.id === active?.scenario.id}
          <div
            role="button"
            tabindex="0"
            onclick={() => (activeId = scenario.id)}
            onkeydown={(e) => e.key === "Enter" && (activeId = scenario.id)}
            class={cn(
              "cursor-pointer rounded-2xl border bg-surface p-5 shadow-[var(--shadow-card)] transition-all",
              isActive ? "border-accent ring-3 ring-accent/15" : "border-line hover:border-line-strong"
            )}
          >
            <div class="flex items-start justify-between gap-2">
              <div class="min-w-0">
                <div class="flex items-center gap-2">
                  <span class="size-2 shrink-0 rounded-full" style="background: {color}"></span>
                  <span class="truncate text-sm font-semibold">{scenario.name}</span>
                </div>
                <div class="num mt-2 text-2xl font-semibold tracking-tight">{yearsLabel(p.yearsToFire)}</div>
                <div class="mt-0.5 text-xs text-muted">
                  {p.fireAge !== null && p.yearsToFire !== 0
                    ? t("mit {age} Jahren ({year})", { age: Math.round(p.fireAge), year: p.fireYear! })
                    : t("FIRE-Zahl {amount}", { amount: fmtEUR0(p.fireNumber) })}
                </div>
              </div>
              <div class="-mr-1.5 -mt-1 flex shrink-0">
                <Button variant="ghost" size="icon-sm" title={t("Bearbeiten")} aria-label={t("Bearbeiten")} onclick={(e) => { e.stopPropagation(); openEdit(scenario); }}><Pencil /></Button>
                <Button variant="ghost" size="icon-sm" class="hover:text-neg" title={t("Löschen")} aria-label={t("Löschen")} onclick={(e) => { e.stopPropagation(); remove(scenario.id); }}><Trash2 /></Button>
              </div>
            </div>
            <div class="mt-4">
              <div class="mb-1.5 flex items-center justify-between text-[11px] text-muted">
                <span class="num">{fmtEUR0(p.start)} / {fmtEUR0(p.fireNumber)}</span>
                <span class="num font-semibold" style="color: {color}">{fmtNum(p.progressPct, 1)} %</span>
              </div>
              <Progress value={p.progressPct} {color} height={6} />
              <div class="mt-2.5 flex flex-wrap gap-x-3 gap-y-0.5 text-[11px] text-faint">
                <span>{fmtEUR0(scenario.params.monthlySavings)}/{t("Mon.")}</span>
                <span>{fmtNum(scenario.params.annualReturnPct, 1)} % {t("Rendite")}</span>
                <span>{fmtNum(scenario.params.withdrawalRatePct, 1)} % SWR</span>
              </div>
            </div>
          </div>
        {/each}
      </div>
    </div>

    <Card>
      <CardHeader title={t("Startkapital")}>
        {#snippet actions()}
          {#if emergency}
            <span class="flex items-center gap-1.5 text-xs text-muted">
              <ShieldCheck class="size-3.5 text-pos" />
              {t("Notgroschen ({amount}) ist ausgenommen", { amount: fmtEUR0(emergency.balance) })}
            </span>
          {/if}
        {/snippet}
      </CardHeader>
      <div class="px-5 pb-5">
        <div class="grid grid-cols-2 gap-3 sm:grid-cols-4">
          {#each ASSET_ROWS as row (row.key)}
            {@const on = active?.scenario.params.include[row.key] ?? true}
            <div class={cn("rounded-xl bg-surface-2 px-4 py-3 transition-opacity", !on && "opacity-40")}>
              <div class="flex items-center gap-2">
                <row.icon class="size-4" style="color: {row.color}" />
                <span class="text-xs text-muted">{row.label}</span>
              </div>
              <div class="num mt-1.5 text-lg font-semibold">{fmtEUR0(assets[row.key])}</div>
            </div>
          {/each}
        </div>
        <p class="mt-3 text-xs text-muted">{t("Welche Bausteine zählen, legst du je Szenario fest — über „Bearbeiten“.")}</p>
      </div>
    </Card>

    <p class="text-xs leading-relaxed text-faint">
      {t("Modell: konstante Realrendite, monatliche Sparrate in heutiger Kaufkraft, FIRE-Zahl = Jahresausgaben ÷ Entnahmerate. Keine Steuern/Abgeltungsteuer, keine Sequence-of-Returns-Risiken — als Orientierung gedacht, nicht als Anlageberatung.")}
    </p>
  </div>
{/if}

<Dialog
  bind:open={editOpen}
  title={isNew ? t("Szenario anlegen") : t("Szenario bearbeiten")}
  description={t("Parameter anpassen — die Vorschau rechnet live mit.")}
  class="max-w-2xl"
>
  <div class="space-y-5">
    <Field label={t("Name")}>
      <Input placeholder={t("z. B. Optimistisch, Sparsam, Basis")} bind:value={draftName} />
    </Field>

    {#if preview}
      <div class="sticky top-0 z-10 -mx-1 grid grid-cols-3 gap-3 rounded-xl bg-accent-soft p-4">
        {#each [
          { l: t("FIRE-Zahl"), v: fmtEUR0(preview.fireNumber) },
          { l: t("Zeit bis FIRE"), v: yearsLabel(preview.yearsToFire) },
          { l: t("Fortschritt"), v: `${fmtNum(preview.progressPct, 1)} %` },
        ] as x (x.l)}
          <div>
            <div class="text-[11px] text-muted">{x.l}</div>
            <div class="num mt-0.5 text-sm font-semibold text-accent">{x.v}</div>
          </div>
        {/each}
      </div>
    {/if}

    {#each SLIDERS as s (s.key)}
      <div>
        <div class="mb-1.5 flex items-center justify-between gap-3 text-[13px]">
          <span class="text-ink-2">{s.label}</span>
          <span class="num shrink-0 font-semibold">{s.fmt(draft[s.key])}</span>
        </div>
        <input type="range" min={s.min} max={s.max} step={s.step} bind:value={draft[s.key]} class="w-full cursor-pointer accent-[var(--accent)]" />
      </div>
    {/each}

    <div>
      <div class="mb-2 text-[13px] text-ink-2">{t("Welches Vermögen zählt ins Startkapital?")}</div>
      <div class="grid grid-cols-1 gap-2 sm:grid-cols-2">
        {#each ASSET_ROWS as row (row.key)}
          {@const on = draft.include[row.key]}
          <button
            type="button"
            onclick={() => (draft.include[row.key] = !on)}
            class={cn(
              "flex cursor-pointer items-center justify-between gap-2 rounded-xl border px-3 py-2.5 text-left text-xs transition-all",
              on ? "border-accent/40 bg-accent-soft" : "border-line text-muted hover:border-line-strong"
            )}
          >
            <span class="flex items-center gap-2">
              <row.icon class="size-4" style={on ? `color: ${row.color}` : undefined} />
              {row.label}
            </span>
            <span class="num">{fmtEUR0(assets[row.key])}</span>
          </button>
        {/each}
      </div>
      <div class="mt-2 flex items-center justify-between text-xs">
        <span class="text-muted">{t("Summe Startkapital")}</span>
        <span class="num font-semibold">{fmtEUR(startCapital({ ...draft, startNetWorth: null }, assets))}</span>
      </div>
    </div>

    <div>
      <div class="mb-2 flex items-center justify-between text-[13px]">
        <span class="text-ink-2">{t("Startkapital überschreiben")}</span>
        <button
          type="button"
          class="cursor-pointer text-xs font-medium text-accent hover:underline"
          onclick={() => (draft.startNetWorth = draft.startNetWorth === null ? Math.round(startCapital({ ...draft, startNetWorth: null }, assets)) : null)}
        >
          {draft.startNetWorth === null ? t("manuell setzen") : t("auf automatisch zurück")}
        </button>
      </div>
      {#if draft.startNetWorth !== null}
        <div class="num mb-1 text-right text-[13px] font-semibold">{fmtEUR0(draft.startNetWorth)}</div>
        <input type="range" min={0} max={2000000} step={5000} bind:value={draft.startNetWorth} class="w-full cursor-pointer accent-[var(--accent)]" />
      {/if}
    </div>
  </div>
  {#snippet footer()}
    <Button variant="secondary" onclick={() => (editOpen = false)} disabled={busy}>{t("Abbrechen")}</Button>
    <Button onclick={save} disabled={busy}>{busy ? t("Speichern …") : t("Speichern")}</Button>
  {/snippet}
</Dialog>

// src/app/fire/page.tsx
"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine,
} from "recharts";
import { Flame, Target, Coins, Plus, Trash2, SlidersHorizontal, Pencil, Wallet, Gem, TrendingUp, PiggyBank, ShieldCheck } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/input";
import { Dialog, DialogContent, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { useI18n } from "@/lib/i18n";
import { DEFAULT_PARAMS, project, startCapital, type Assets, type FireParams } from "@/lib/fire";
import { apiJson, cn, fmtEUR, fmtEUR0, fmtNum } from "@/lib/utils";

type Scenario = { id: number; name: string; createdAt: string; params: FireParams };

const COLORS = ["#d4af37", "#38bdf8", "#a78bfa", "#34d399", "#fb923c", "#f472b6"];

export default function FirePage() {
  const { t } = useI18n();
  const [scenarios, setScenarios] = useState<Scenario[] | null>(null);
  const [assets, setAssets] = useState<Assets>({ cash: 0, metals: 0, investments: 0, pension: 0 });
  const [emergency, setEmergency] = useState<{ balance: number; accountName: string } | null>(null);
  const [activeId, setActiveId] = useState<number | null>(null);
  const [editing, setEditing] = useState<Scenario | null>(null);
  const [draft, setDraft] = useState<FireParams>(DEFAULT_PARAMS);
  const [draftName, setDraftName] = useState("");
  const [isNew, setIsNew] = useState(false);
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    const [f, s] = await Promise.all([
      apiJson<{ scenarios: Scenario[] }>("/api/fire"),
      apiJson<{ assets?: Assets; emergency?: { balance: number; accountName: string } | null }>("/api/summary"),
    ]);
    setAssets(s.assets ?? { cash: 0, metals: 0, investments: 0, pension: 0 });
    setEmergency(s.emergency ? { balance: s.emergency.balance, accountName: s.emergency.accountName } : null);
    setScenarios(f.scenarios);
    setActiveId((prev) => prev ?? f.scenarios[0]?.id ?? null);
  }, []);
  useEffect(() => { load(); }, [load]);

  const openEdit = (s: Scenario) => { setEditing(s); setDraft(s.params); setDraftName(s.name); setIsNew(false); };
  const openNew = () => {
    const base = scenarios?.find((s) => s.id === activeId)?.params ?? DEFAULT_PARAMS;
    setEditing({ id: -1, name: "", createdAt: "", params: base });
    setDraft(base);
    setDraftName("");
    setIsNew(true);
  };

  const save = async () => {
    setBusy(true);
    if (isNew) {
      const res = await fetch("/api/fire", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ name: draftName || t("Neues Szenario"), params: draft }),
      });
      const d = await res.json();
      if (res.ok) setActiveId(d.id);
    } else {
      await fetch("/api/fire", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id: editing!.id, name: draftName, params: draft }),
      });
    }
    setBusy(false);
    setEditing(null);
    load();
  };

  const remove = async (id: number) => {
    if (!confirm(t("Szenario wirklich löschen?"))) return;
    const res = await fetch(`/api/fire?id=${id}`, { method: "DELETE" });
    if (!res.ok) { alert((await res.json()).error); return; }
    if (activeId === id) setActiveId(null);
    load();
  };

  // Live-Vorschau im Modal
  const previewProjection = useMemo(
    () => (editing ? project(draft, assets, new Date().getFullYear()) : null),
    [editing, draft, assets]
  );

  const projections = useMemo(() => {
    const year = new Date().getFullYear();
    return (scenarios ?? []).map((s) => ({ scenario: s, p: project(s.params, assets, year) }));
  }, [scenarios, assets]);

  const active = projections.find((x) => x.scenario.id === activeId) ?? projections[0];

  const ASSET_ROWS: Array<{ key: keyof Assets; label: string; icon: typeof Wallet; color: string }> = [
    { key: "cash", label: t("Liquidität"), icon: Wallet, color: "#38bdf8" },
    { key: "investments", label: t("Investments"), icon: TrendingUp, color: "#a78bfa" },
    { key: "metals", label: t("Edelmetalle"), icon: Gem, color: "#d4af37" },
    { key: "pension", label: t("Altersvorsorge"), icon: PiggyBank, color: "#34d399" },
  ];

  const SLIDERS: Array<{ key: keyof FireParams; label: string; min: number; max: number; step: number; fmt: (v: number) => string }> = [
    { key: "age", label: t("Aktuelles Alter"), min: 18, max: 70, step: 1, fmt: (v) => t("{n} Jahre", { n: v }) },
    { key: "monthlySavings", label: t("Sparrate / Monat"), min: 0, max: 10000, step: 50, fmt: (v) => fmtEUR0(v) },
    { key: "monthlyExpenses", label: t("Wunsch-Ausgaben im Ruhestand / Monat (heutige Kaufkraft)"), min: 500, max: 15000, step: 100, fmt: (v) => fmtEUR0(v) },
    { key: "annualReturnPct", label: t("Erwartete Rendite p. a."), min: 0, max: 12, step: 0.1, fmt: (v) => `${fmtNum(v, 1)} %` },
    { key: "inflationPct", label: t("Inflation p. a."), min: 0, max: 6, step: 0.1, fmt: (v) => `${fmtNum(v, 1)} %` },
    { key: "withdrawalRatePct", label: t("Entnahmerate (SWR)"), min: 2, max: 6, step: 0.1, fmt: (v) => `${fmtNum(v, 1)} %` },
  ];

  if (!scenarios) {
    return <div className="flex h-[70vh] items-center justify-center text-sm text-muted-2 animate-pulse">{t("Lade Simulator …")}</div>;
  }

  return (
    <div className="space-y-6">
      <div className="rise flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-4xl gold-text">{t("FIRE-Simulator")}</h1>
          <p className="mt-1 max-w-2xl text-sm text-muted-2">
            {t("Financial Independence, Retire Early — alle Werte inflationsbereinigt in heutiger Kaufkraft.")}
          </p>
        </div>
        <Button size="sm" onClick={openNew}><Plus className="h-4 w-4" /> {t("Szenario anlegen")}</Button>
      </div>

      {/* Vermögensbausteine */}
      <Card className="rise rise-1">
        <CardHeader className="flex-row flex-wrap items-center justify-between gap-2">
          <CardTitle>{t("Startkapital")}</CardTitle>
          {emergency && (
            <span className="flex items-center gap-1.5 text-[11px] text-muted-2">
              <ShieldCheck className="h-3.5 w-3.5 text-emerald-soft" />
              {t("Notgroschen ({amount}) ist ausgenommen", { amount: fmtEUR0(emergency.balance) })}
            </span>
          )}
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
            {ASSET_ROWS.map(({ key, label, icon: Icon, color }) => {
              const on = active?.scenario.params.include[key] ?? true;
              return (
                <div
                  key={key}
                  className={cn(
                    "rounded-xl border px-4 py-3 transition-opacity",
                    on ? "border-white/12 bg-white/[0.04]" : "border-white/5 opacity-40"
                  )}
                >
                  <div className="flex items-center gap-2">
                    <Icon className="h-4 w-4" style={{ color }} strokeWidth={1.8} />
                    <span className="text-[11px] uppercase tracking-wider text-muted-2">{label}</span>
                  </div>
                  <div className="num mt-1.5 text-lg font-semibold">{fmtEUR0(assets[key])}</div>
                </div>
              );
            })}
          </div>
          <p className="mt-3 text-[11px] text-muted-2">
            {t("Welche Bausteine zählen, legst du je Szenario fest — über „Bearbeiten“.")}
          </p>
        </CardContent>
      </Card>

      {/* Szenarien */}
      <div className="grid grid-cols-1 gap-4 lg:grid-cols-2 xl:grid-cols-3">
        {projections.map(({ scenario, p }, i) => {
          const color = COLORS[i % COLORS.length];
          const isActive = scenario.id === activeId;
          return (
            <Card
              key={scenario.id}
              className={cn("rise glass-hover cursor-pointer p-5 transition-all", isActive && "border-gold/40")}
              style={isActive ? { boxShadow: `0 0 32px -12px ${color}80` } : undefined}
              onClick={() => setActiveId(scenario.id)}
            >
              <div className="flex items-start justify-between gap-2">
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <span className="h-2 w-2 shrink-0 rounded-full" style={{ background: color }} />
                    <span className="truncate text-sm font-semibold">{scenario.name}</span>
                  </div>
                  <div className="num mt-2 text-2xl font-semibold tracking-tight">
                    {p.yearsToFire === null ? t("> 60 J.") : p.yearsToFire === 0 ? t("Erreicht 🎉") : t("{n} Jahre", { n: fmtNum(p.yearsToFire, 1) })}
                  </div>
                  <div className="mt-0.5 text-xs text-muted-2">
                    {p.fireAge !== null && p.yearsToFire !== 0
                      ? t("mit {age} Jahren ({year})", { age: Math.round(p.fireAge), year: p.fireYear! })
                      : t("FIRE-Zahl {amount}", { amount: fmtEUR0(p.fireNumber) })}
                  </div>
                </div>
                <div className="flex shrink-0 gap-1">
                  <button
                    onClick={(e) => { e.stopPropagation(); openEdit(scenario); }}
                    className="rounded-lg p-1.5 text-muted-2 transition-colors hover:bg-white/8 hover:text-foreground cursor-pointer"
                    title={t("Bearbeiten")}
                  >
                    <Pencil className="h-3.5 w-3.5" />
                  </button>
                  <button
                    onClick={(e) => { e.stopPropagation(); remove(scenario.id); }}
                    className="rounded-lg p-1.5 text-muted-2 transition-colors hover:bg-rose-soft/10 hover:text-rose-soft cursor-pointer"
                    title={t("Löschen")}
                  >
                    <Trash2 className="h-3.5 w-3.5" />
                  </button>
                </div>
              </div>

              {/* Fortschritt je Szenario */}
              <div className="mt-4">
                <div className="mb-1.5 flex items-center justify-between text-[11px] text-muted-2">
                  <span className="num">{fmtEUR0(p.start)} / {fmtEUR0(p.fireNumber)}</span>
                  <span className="num font-semibold" style={{ color }}>{fmtNum(p.progressPct, 1)} %</span>
                </div>
                <div className="h-2 overflow-hidden rounded-full bg-white/[0.06]">
                  <div
                    className="h-full rounded-full transition-all duration-700"
                    style={{ width: `${p.progressPct}%`, background: `linear-gradient(90deg, ${color}90, ${color})`, boxShadow: `0 0 12px ${color}60` }}
                  />
                </div>
                <div className="mt-2 flex flex-wrap gap-x-3 gap-y-0.5 text-[10px] text-muted-2">
                  <span>{fmtEUR0(scenario.params.monthlySavings)}/{t("Mon.")}</span>
                  <span>{fmtNum(scenario.params.annualReturnPct, 1)} % {t("Rendite")}</span>
                  <span>{fmtNum(scenario.params.withdrawalRatePct, 1)} % SWR</span>
                </div>
              </div>
            </Card>
          );
        })}
      </div>

      {/* Kennzahlen des aktiven Szenarios */}
      {active && (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
          {[
            { icon: Target, label: t("FIRE-Zahl"), value: fmtEUR0(active.p.fireNumber), sub: t("bei {pct} % Entnahme", { pct: fmtNum(active.scenario.params.withdrawalRatePct, 1) }), accent: "#d4af37" },
            { icon: Coins, label: t("Startkapital"), value: fmtEUR0(active.p.start), sub: active.scenario.params.startNetWorth === null ? t("aus gewählten Bausteinen") : t("manuell gesetzt"), accent: "#38bdf8" },
            { icon: Flame, label: t("Fortschritt"), value: `${fmtNum(active.p.progressPct, 1)} %`, sub: t("{amount} fehlen", { amount: fmtEUR0(Math.max(0, active.p.fireNumber - active.p.start)) }), accent: "#fb923c" },
            { icon: SlidersHorizontal, label: t("Realrendite"), value: `${fmtNum(active.p.realAnnualPct, 1)} %`, sub: t("nach Inflation"), accent: "#a78bfa" },
          ].map(({ icon: Icon, label, value, sub, accent }) => (
            <Card key={label} className="glass-hover rise p-6">
              <div className="flex items-start justify-between">
                <div>
                  <div className="text-[11px] uppercase tracking-[0.18em] text-muted-2">{label}</div>
                  <div className="num mt-2 text-2xl font-semibold tracking-tight">{value}</div>
                  <div className="mt-1 text-xs text-muted-2">{sub}</div>
                </div>
                <div className="rounded-xl p-2.5" style={{ background: `${accent}14`, border: `1px solid ${accent}30` }}>
                  <Icon className="h-5 w-5" style={{ color: accent }} strokeWidth={1.8} />
                </div>
              </div>
            </Card>
          ))}
        </div>
      )}

      {/* Vergleich aller Szenarien */}
      <Card className="rise rise-4">
        <CardHeader className="flex-row flex-wrap items-center justify-between gap-2">
          <CardTitle>{t("Vermögensprojektion (real)")}</CardTitle>
          <div className="flex flex-wrap gap-3 text-[11px] text-muted">
            {projections.map(({ scenario }, i) => (
              <span key={scenario.id} className="flex items-center gap-1.5">
                <span className="h-2 w-2 rounded-full" style={{ background: COLORS[i % COLORS.length] }} />
                {scenario.name}
              </span>
            ))}
          </div>
        </CardHeader>
        <CardContent className="h-[420px]">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart margin={{ top: 10, right: 10, bottom: 0, left: 10 }}>
              <defs>
                {projections.map(({ scenario }, i) => (
                  <linearGradient key={scenario.id} id={`gF${scenario.id}`} x1="0" y1="0" x2="0" y2="1">
                    <stop offset="0%" stopColor={COLORS[i % COLORS.length]} stopOpacity={0.3} />
                    <stop offset="100%" stopColor={COLORS[i % COLORS.length]} stopOpacity={0} />
                  </linearGradient>
                ))}
              </defs>
              <CartesianGrid stroke="rgba(255,255,255,0.05)" vertical={false} />
              <XAxis
                dataKey="age" type="number" domain={["dataMin", "dataMax"]}
                axisLine={false} tickLine={false} dy={8}
                tickFormatter={(v: number) => t("{n} J.", { n: Math.round(v) })}
                allowDuplicatedCategory={false}
              />
              <YAxis
                axisLine={false} tickLine={false} width={64}
                tickFormatter={(v: number) => (v >= 1_000_000 ? `${fmtNum(v / 1_000_000, 1)} M` : `${Math.round(v / 1000)}k`)}
              />
              <Tooltip
                content={({ active: a, payload }) => {
                  if (!a || !payload?.length) return null;
                  return (
                    <div className="glass rounded-xl px-4 py-3 text-xs">
                      <div className="mb-1 text-muted">{t("Alter {age}", { age: Math.round(payload[0].payload.age) })}</div>
                      {payload.map((pl) => (
                        <div key={String(pl.name)} className="flex items-center justify-between gap-4">
                          <span className="flex items-center gap-1.5">
                            <span className="h-2 w-2 rounded-full" style={{ background: pl.stroke }} />
                            {pl.name}
                          </span>
                          <span className="num font-semibold">{fmtEUR0(Number(pl.value))}</span>
                        </div>
                      ))}
                    </div>
                  );
                }}
              />
              {active && <ReferenceLine y={active.p.fireNumber} stroke="#fb923c" strokeDasharray="6 4" strokeWidth={1.5} />}
              {projections.map(({ scenario, p }, i) => (
                <Area
                  key={scenario.id}
                  data={p.series}
                  dataKey="value"
                  name={scenario.name}
                  stroke={COLORS[i % COLORS.length]}
                  strokeWidth={scenario.id === activeId ? 2.5 : 1.5}
                  strokeOpacity={scenario.id === activeId ? 1 : 0.45}
                  fill={scenario.id === activeId ? `url(#gF${scenario.id})` : "transparent"}
                />
              ))}
            </AreaChart>
          </ResponsiveContainer>
        </CardContent>
      </Card>

      <p className="rise rise-5 text-[11px] leading-relaxed text-muted-2">
        {t("Modell: konstante Realrendite, monatliche Sparrate in heutiger Kaufkraft, FIRE-Zahl = Jahresausgaben ÷ Entnahmerate. Keine Steuern/Abgeltungsteuer, keine Sequence-of-Returns-Risiken — als Orientierung gedacht, nicht als Anlageberatung.")}
      </p>

      {/* Rechner im Modal */}
      <Dialog open={editing !== null} onOpenChange={(o) => !o && setEditing(null)}>
        <DialogContent className="max-h-[88vh] max-w-2xl overflow-y-auto">
          <DialogTitle>{isNew ? t("Szenario anlegen") : t("Szenario bearbeiten")}</DialogTitle>
          <DialogDescription>{t("Parameter anpassen — die Vorschau rechnet live mit.")}</DialogDescription>

          <div className="mt-5 space-y-5">
            <div className="space-y-1.5">
              <Label>{t("Name")}</Label>
              <Input
                autoFocus={isNew}
                placeholder={t("z. B. Optimistisch, Sparsam, Basis")}
                value={draftName}
                onChange={(e) => setDraftName(e.target.value)}
              />
            </div>

            {previewProjection && (
              <div className="glass-inset grid grid-cols-3 gap-3 rounded-xl p-4">
                {[
                  { l: t("FIRE-Zahl"), v: fmtEUR0(previewProjection.fireNumber) },
                  {
                    l: t("Zeit bis FIRE"),
                    v: previewProjection.yearsToFire === null ? t("> 60 J.")
                      : previewProjection.yearsToFire === 0 ? t("Erreicht 🎉")
                      : t("{n} Jahre", { n: fmtNum(previewProjection.yearsToFire, 1) }),
                  },
                  { l: t("Fortschritt"), v: `${fmtNum(previewProjection.progressPct, 1)} %` },
                ].map(({ l, v }) => (
                  <div key={l}>
                    <div className="text-[10px] uppercase tracking-wider text-muted-2">{l}</div>
                    <div className="num mt-0.5 text-sm font-semibold text-gold-bright">{v}</div>
                  </div>
                ))}
              </div>
            )}

            {SLIDERS.map(({ key, label, min, max, step, fmt }) => (
              <div key={key}>
                <div className="mb-2 flex items-center justify-between text-sm">
                  <span className="text-muted">{label}</span>
                  <span className="num font-semibold text-gold-bright">{fmt(draft[key] as number)}</span>
                </div>
                <input
                  type="range"
                  min={min} max={max} step={step}
                  value={draft[key] as number}
                  onChange={(e) => setDraft({ ...draft, [key]: Number(e.target.value) })}
                  className="w-full accent-[#d4af37] cursor-pointer"
                />
              </div>
            ))}

            <div>
              <div className="mb-2 text-sm text-muted">{t("Welches Vermögen zählt ins Startkapital?")}</div>
              <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
                {ASSET_ROWS.map(({ key, label, icon: Icon, color }) => {
                  const on = draft.include[key];
                  return (
                    <button
                      key={key}
                      onClick={() => setDraft({ ...draft, include: { ...draft.include, [key]: !on } })}
                      className={cn(
                        "flex cursor-pointer items-center justify-between gap-2 rounded-xl border px-3 py-2.5 text-left text-xs transition-all",
                        on ? "border-gold/35 bg-gold/8" : "border-white/10 text-muted-2 hover:border-white/20"
                      )}
                    >
                      <span className="flex items-center gap-2">
                        <Icon className="h-4 w-4" style={{ color: on ? color : undefined }} strokeWidth={1.8} />
                        {label}
                      </span>
                      <span className="num">{fmtEUR0(assets[key])}</span>
                    </button>
                  );
                })}
              </div>
              <div className="mt-2 flex items-center justify-between text-[11px]">
                <span className="text-muted-2">{t("Summe Startkapital")}</span>
                <span className="num font-semibold text-gold-bright">
                  {fmtEUR(startCapital({ ...draft, startNetWorth: null }, assets))}
                </span>
              </div>
            </div>

            <div>
              <div className="mb-2 flex items-center justify-between text-sm">
                <span className="text-muted">{t("Startkapital überschreiben")}</span>
                <button
                  className="text-xs text-gold-bright hover:underline cursor-pointer"
                  onClick={() =>
                    setDraft({
                      ...draft,
                      startNetWorth: draft.startNetWorth === null
                        ? Math.round(startCapital({ ...draft, startNetWorth: null }, assets))
                        : null,
                    })
                  }
                >
                  {draft.startNetWorth === null ? t("manuell setzen") : t("auf automatisch zurück")}
                </button>
              </div>
              {draft.startNetWorth !== null && (
                <input
                  type="range" min={0} max={2000000} step={5000}
                  value={draft.startNetWorth}
                  onChange={(e) => setDraft({ ...draft, startNetWorth: Number(e.target.value) })}
                  className="w-full accent-[#d4af37] cursor-pointer"
                />
              )}
            </div>
          </div>

          <div className="mt-6 flex gap-3">
            <Button variant="outline" className="flex-1" onClick={() => setEditing(null)} disabled={busy}>{t("Abbrechen")}</Button>
            <Button className="flex-1" onClick={save} disabled={busy}>{busy ? t("Speichern …") : t("Speichern")}</Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
