// src/routes/login/+page.svelte
<script lang="ts">
  import { LogIn } from "@lucide/svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import Field from "$lib/components/ui/Field.svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import Alert from "$lib/components/ui/Alert.svelte";
  import AuthFrame from "$lib/components/AuthFrame.svelte";
  import { t } from "$lib/i18n";

  let username = $state("");
  let password = $state("");
  let busy = $state(false);
  let error = $state<string | null>(null);

  async function submit(e: SubmitEvent) {
    e.preventDefault();
    busy = true;
    error = null;
    const res = await fetch("/api/auth/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username, password }),
    });
    busy = false;
    if (!res.ok) {
      // The lockout message carries an {n} placeholder — without the seconds
      // it would appear on screen literally.
      const d = await res.json();
      error = t(d.error, d.seconds !== undefined ? { n: d.seconds } : undefined);
      return;
    }
    // Full load, not client navigation: the layout's server data (auth state)
    // must be fetched fresh with the new cookie.
    window.location.href = "/";
  }
</script>

<svelte:head><title>{t("Anmelden")} · Achilles</title></svelte:head>

<AuthFrame>
  <Card class="p-6">
    <form onsubmit={submit} class="space-y-4">
      <Field label={t("Benutzername")}>
        <!-- svelte-ignore a11y_autofocus -->
        <Input autofocus autocomplete="username" bind:value={username} oninput={() => (error = null)} />
      </Field>
      <Field label={t("Passwort")}>
        <Input type="password" autocomplete="current-password" bind:value={password} oninput={() => (error = null)} />
      </Field>
      {#if error}<Alert tone="neg">{error}</Alert>{/if}
      <Button type="submit" class="w-full" disabled={busy || !username || !password}>
        <LogIn /> {busy ? t("Anmelden …") : t("Anmelden")}
      </Button>
    </form>
  </Card>
  <p class="mt-4 text-center text-xs leading-relaxed text-muted">
    {t("Passwort vergessen? Es lässt sich nur direkt in der Datenbank zurücksetzen — siehe README.")}
  </p>
</AuthFrame>

// src/app/login/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Shield, LogIn, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label } from "@/components/ui/input";
import { useI18n } from "@/lib/i18n";

export default function LoginPage() {
  const { t } = useI18n();
  const router = useRouter();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    setBusy(true);
    setError(null);
    const res = await fetch("/api/auth/login", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ username, password }),
    });
    setBusy(false);
    if (!res.ok) { setError(t((await res.json()).error)); return; }
    router.replace("/");
    router.refresh();
  };

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <div className="aurora" />
      <div className="rise w-full max-w-sm">
        <div className="mb-8 flex flex-col items-center gap-3 text-center">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-[#e9cd6f] to-[#9a7a26] shadow-[0_16px_40px_-10px_rgba(212,175,55,0.6)]">
            <Shield className="h-8 w-8 text-[#1a1405]" strokeWidth={2} />
          </div>
          <div>
            <div className="font-display text-3xl gold-text">Achilles Financials</div>
            <div className="mt-1 text-[11px] uppercase tracking-[0.28em] text-muted-2">Private Wealth Dashboard</div>
          </div>
        </div>

        <form onSubmit={submit} className="glass space-y-4 rounded-glass p-7">
          <div className="space-y-1.5">
            <Label>{t("Benutzername")}</Label>
            <Input autoFocus autoComplete="username" value={username} onChange={(e) => { setUsername(e.target.value); setError(null); }} />
          </div>
          <div className="space-y-1.5">
            <Label>{t("Passwort")}</Label>
            <Input type="password" autoComplete="current-password" value={password} onChange={(e) => { setPassword(e.target.value); setError(null); }} />
          </div>

          {error && (
            <div className="flex items-center gap-2 rounded-xl border border-rose-soft/25 bg-rose-soft/8 px-3 py-2.5 text-xs text-rose-soft">
              <AlertTriangle className="h-3.5 w-3.5 shrink-0" /> {error}
            </div>
          )}

          <Button type="submit" className="w-full" disabled={busy || !username || !password}>
            <LogIn className="h-4 w-4" /> {busy ? t("Anmelden …") : t("Anmelden")}
          </Button>
        </form>

        <p className="mt-4 text-center text-[11px] leading-relaxed text-muted-2">
          {t("Passwort vergessen? Es lässt sich nur direkt in der Datenbank zurücksetzen — siehe README.")}
        </p>
      </div>
    </div>
  );
}
