// src/routes/setup/+page.svelte
<script lang="ts">
  import { Sparkles, Database, KeyRound, Check } from "@lucide/svelte";
  import Button from "$lib/components/ui/Button.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import Textarea from "$lib/components/ui/Textarea.svelte";
  import Field from "$lib/components/ui/Field.svelte";
  import Select from "$lib/components/ui/Select.svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import Alert from "$lib/components/ui/Alert.svelte";
  import AuthFrame from "$lib/components/AuthFrame.svelte";
  import { t } from "$lib/i18n";
  import { prefs, setLang, type Lang } from "$lib/prefs.svelte";
  import { COUNTRIES } from "$lib/countries";
  import { cn } from "$lib/utils";

  let step = $state(0);
  let appId = $state("");
  let privateKey = $state("");
  let country = $state("DE");
  let startMode = $state<"demo" | "empty">("demo");
  let busy = $state(false);
  let error = $state<string | null>(null);

  async function finish() {
    busy = true;
    error = null;
    const res = await fetch("/api/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        language: prefs.lang,
        country,
        ebAppId: appId || undefined,
        ebPrivateKey: privateKey || undefined,
        setupDone: true,
      }),
    });
    if (!res.ok) { busy = false; error = (await res.json()).error; step = 1; return; }
    if (startMode === "demo") await fetch("/api/demo", { method: "POST" });
    window.location.href = "/";
  }

  const STEPS = $derived([t("Sprache"), "Enable Banking", "Start"]);

  const choice = (on: boolean) =>
    cn(
      "cursor-pointer rounded-2xl border p-5 text-left transition-all",
      on ? "border-accent bg-accent-soft ring-3 ring-accent/15" : "border-line bg-surface hover:border-line-strong"
    );
</script>

<svelte:head><title>Setup · Achilles</title></svelte:head>

<AuthFrame width="max-w-xl">
  <!-- Step indicator -->
  <div class="mb-5 flex items-center justify-center gap-2">
    {#each STEPS as label, i (label)}
      <div class="flex items-center gap-2">
        <span
          class={cn(
            "flex size-7 items-center justify-center rounded-full text-xs font-semibold transition-all",
            i < step ? "bg-accent-soft text-accent" : i === step ? "bg-accent text-accent-ink" : "bg-surface-3 text-faint"
          )}
          title={label}
        >
          {#if i < step}<Check class="size-3.5" />{:else}{i + 1}{/if}
        </span>
        {#if i < STEPS.length - 1}<span class={cn("h-px w-10", i < step ? "bg-accent/50" : "bg-line-strong")}></span>{/if}
      </div>
    {/each}
  </div>

  <Card class="p-7">
    {#if step === 0}
      <div class="space-y-6">
        <h2 class="text-center text-lg font-semibold">{t("Sprache wählen / Choose your language")}</h2>
        <div class="grid grid-cols-2 gap-4">
          {#each [["de", "Deutsch", "🇩🇪"], ["en", "English", "🇬🇧"]] as [code, label, flag] (code)}
            <button type="button" onclick={() => setLang(code as Lang)} class={cn(choice(prefs.lang === code), "text-center")}>
              <div class="text-3xl">{flag}</div>
              <div class="mt-2 text-sm font-medium">{label}</div>
            </button>
          {/each}
        </div>
        <Button class="w-full" onclick={() => (step = 1)}>{t("Weiter")}</Button>
      </div>
    {:else if step === 1}
      <div class="space-y-5">
        <div class="flex items-start gap-3">
          <span class="flex size-10 shrink-0 items-center justify-center rounded-xl bg-accent-soft text-accent"><KeyRound class="size-5" /></span>
          <div>
            <h2 class="text-lg font-semibold">{t("Bankanbindung (optional)")}</h2>
            <p class="text-xs text-muted">{t("Application-ID und Private Key aus deinem Enable-Banking-Control-Panel (enablebanking.com).")}</p>
          </div>
        </div>
        <div class="space-y-4">
          <Field label="Application ID">
            <Input placeholder="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" bind:value={appId} />
          </Field>
          <Field label={t("Private Key (.pem-Inhalt)")}>
            <Textarea rows={3} spellcheck={false} class="font-mono text-[11px]" placeholder={"-----BEGIN PRIVATE KEY-----\n…\n-----END PRIVATE KEY-----"} bind:value={privateKey} />
          </Field>
          <Field label={t("Land deiner Bank")}>
            <Select bind:value={country} options={COUNTRIES.map((c) => ({ value: c.code, label: prefs.lang === "de" ? c.de : c.en }))} />
          </Field>
        </div>
        {#if error}<Alert tone="neg">{error}</Alert>{/if}
        <p class="text-xs leading-relaxed text-muted">
          {t("Du kannst das jederzeit später in den Einstellungen nachholen — oder Kontoauszüge per CSV importieren.")}
        </p>
        <div class="flex gap-3">
          <Button variant="secondary" class="flex-1" onclick={() => (step = 0)}>{t("Zurück")}</Button>
          <Button class="flex-1" onclick={() => (step = 2)}>{appId && privateKey ? t("Weiter") : t("Überspringen")}</Button>
        </div>
      </div>
    {:else}
      <div class="space-y-6">
        <h2 class="text-center text-lg font-semibold">{t("Wie möchtest du starten?")}</h2>
        <div class="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <button type="button" onclick={() => (startMode = "demo")} class={choice(startMode === "demo")}>
            <Sparkles class={cn("size-6", startMode === "demo" ? "text-accent" : "text-faint")} />
            <div class="mt-3 text-sm font-semibold">{t("Mit Demo-Daten erkunden")}</div>
            <div class="mt-1 text-xs leading-relaxed text-muted">{t("Realistische Beispieldaten — jederzeit in den Einstellungen entfernbar.")}</div>
          </button>
          <button type="button" onclick={() => (startMode = "empty")} class={choice(startMode === "empty")}>
            <Database class={cn("size-6", startMode === "empty" ? "text-accent" : "text-faint")} />
            <div class="mt-3 text-sm font-semibold">{t("Leer starten")}</div>
            <div class="mt-1 text-xs leading-relaxed text-muted">{t("Direkt mit deinen echten Daten loslegen.")}</div>
          </button>
        </div>
        <div class="flex gap-3">
          <Button variant="secondary" class="flex-1" onclick={() => (step = 1)} disabled={busy}>{t("Zurück")}</Button>
          <Button class="flex-1" onclick={finish} disabled={busy}>{busy ? t("Einen Moment …") : t("Los geht's")}</Button>
        </div>
      </div>
    {/if}
  </Card>
</AuthFrame>

// src/app/setup/page.tsx
"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Shield, Sparkles, Database, KeyRound, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input, Label, Select } from "@/components/ui/input";
import { useI18n, type Lang } from "@/lib/i18n";
import { COUNTRIES } from "@/lib/countries";
import { cn } from "@/lib/utils";

export default function SetupPage() {
  const { t, lang, setLang } = useI18n();
  const router = useRouter();
  const [step, setStep] = useState(0);
  const [appId, setAppId] = useState("");
  const [privateKey, setPrivateKey] = useState("");
  const [country, setCountry] = useState("DE");
  const [startMode, setStartMode] = useState<"demo" | "empty">("demo");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const finish = async () => {
    setBusy(true);
    setError(null);
    const res = await fetch("/api/settings", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        language: lang,
        country,
        ebAppId: appId || undefined,
        ebPrivateKey: privateKey || undefined,
        setupDone: true,
      }),
    });
    if (!res.ok) { setBusy(false); setError((await res.json()).error); setStep(1); return; }
    if (startMode === "demo") await fetch("/api/demo", { method: "POST" });
    router.replace("/");
  };

  const STEPS = [t("Sprache"), "Enable Banking", "Start"];

  return (
    <div className="flex min-h-screen items-center justify-center p-4">
      <div className="rise w-full max-w-xl">
        {/* Logo */}
        <div className="mb-8 flex flex-col items-center gap-3 text-center">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-gradient-to-br from-[#e9cd6f] to-[#9a7a26] shadow-[0_16px_40px_-10px_rgba(212,175,55,0.6)]">
            <Shield className="h-8 w-8 text-[#1a1405]" strokeWidth={2} />
          </div>
          <div>
            <div className="font-display text-3xl gold-text">Achilles Financials</div>
            <div className="mt-1 text-[11px] uppercase tracking-[0.28em] text-muted-2">Private Wealth Dashboard</div>
          </div>
        </div>

        {/* Step indicator */}
        <div className="mb-6 flex items-center justify-center gap-2">
          {STEPS.map((label, i) => (
            <div key={label} className="flex items-center gap-2">
              <div
                className={cn(
                  "flex h-7 w-7 items-center justify-center rounded-full border text-xs font-semibold transition-all",
                  i < step ? "border-gold/40 bg-gold/20 text-gold-bright"
                    : i === step ? "border-gold bg-gold text-[#1a1405]"
                    : "border-white/15 text-muted-2"
                )}
              >
                {i < step ? <Check className="h-3.5 w-3.5" /> : i + 1}
              </div>
              {i < STEPS.length - 1 && <div className={cn("h-px w-10", i < step ? "bg-gold/50" : "bg-white/10")} />}
            </div>
          ))}
        </div>

        <div className="glass rounded-glass p-8">
          {/* Step 0: Sprache */}
          {step === 0 && (
            <div className="space-y-6">
              <h2 className="text-center text-lg font-semibold">{t("Sprache wählen / Choose your language")}</h2>
              <div className="grid grid-cols-2 gap-4">
                {([["de", "Deutsch", "🇩🇪"], ["en", "English", "🇬🇧"]] as Array<[Lang, string, string]>).map(([code, label, flag]) => (
                  <button
                    key={code}
                    onClick={() => setLang(code)}
                    className={cn(
                      "cursor-pointer rounded-2xl border p-6 text-center transition-all",
                      lang === code
                        ? "border-gold/50 bg-gold/10 shadow-[0_0_32px_-8px_rgba(212,175,55,0.5)]"
                        : "border-white/10 hover:border-white/25"
                    )}
                  >
                    <div className="text-3xl">{flag}</div>
                    <div className={cn("mt-2 text-sm font-medium", lang === code ? "text-gold-bright" : "text-muted")}>{label}</div>
                  </button>
                ))}
              </div>
              <Button className="w-full" onClick={() => setStep(1)}>{t("Weiter")}</Button>
            </div>
          )}

          {/* Step 1: Enable Banking (optional) */}
          {step === 1 && (
            <div className="space-y-5">
              <div className="flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gold/10 border border-gold/20">
                  <KeyRound className="h-5 w-5 text-gold" strokeWidth={1.7} />
                </div>
                <div>
                  <h2 className="text-lg font-semibold">{t("Bankanbindung (optional)")}</h2>
                  <p className="text-xs text-muted-2">{t("Application-ID und Private Key aus deinem Enable-Banking-Control-Panel (enablebanking.com).")}</p>
                </div>
              </div>
              <div className="space-y-4">
                <div className="space-y-1.5">
                  <Label>Application ID</Label>
                  <Input placeholder="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee" value={appId} onChange={(e) => setAppId(e.target.value)} />
                </div>
                <div className="space-y-1.5">
                  <Label>{t("Private Key (.pem-Inhalt)")}</Label>
                  <textarea
                    rows={3}
                    spellCheck={false}
                    placeholder={"-----BEGIN PRIVATE KEY-----\n…\n-----END PRIVATE KEY-----"}
                    value={privateKey}
                    onChange={(e) => setPrivateKey(e.target.value)}
                    className="flex w-full rounded-xl glass-inset px-4 py-3 font-mono text-[11px] text-foreground placeholder:text-muted-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold/40"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label>{t("Land deiner Bank")}</Label>
                  <Select value={country} onChange={(e) => setCountry(e.target.value)}>
                    {COUNTRIES.map((c) => (
                      <option key={c.code} value={c.code}>{lang === "de" ? c.de : c.en}</option>
                    ))}
                  </Select>
                </div>
              </div>
              {error && (
                <div className="rounded-xl border border-rose-soft/25 bg-rose-soft/8 px-4 py-3 text-xs text-rose-soft">{error}</div>
              )}
              <p className="text-[11px] leading-relaxed text-muted-2">
                {t("Du kannst das jederzeit später in den Einstellungen nachholen — oder Kontoauszüge per CSV importieren.")}
              </p>
              <div className="flex gap-3">
                <Button variant="outline" className="flex-1" onClick={() => setStep(0)}>{t("Zurück")}</Button>
                <Button className="flex-1" onClick={() => setStep(2)}>
                  {appId && privateKey ? t("Weiter") : t("Überspringen")}
                </Button>
              </div>
            </div>
          )}

          {/* Step 2: Start mode */}
          {step === 2 && (
            <div className="space-y-6">
              <h2 className="text-center text-lg font-semibold">{t("Wie möchtest du starten?")}</h2>
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <button
                  onClick={() => setStartMode("demo")}
                  className={cn(
                    "cursor-pointer rounded-2xl border p-6 text-left transition-all",
                    startMode === "demo" ? "border-gold/50 bg-gold/10 shadow-[0_0_32px_-8px_rgba(212,175,55,0.5)]" : "border-white/10 hover:border-white/25"
                  )}
                >
                  <Sparkles className={cn("h-6 w-6", startMode === "demo" ? "text-gold" : "text-muted-2")} strokeWidth={1.6} />
                  <div className={cn("mt-3 text-sm font-medium", startMode === "demo" ? "text-gold-bright" : "text-foreground")}>{t("Mit Demo-Daten erkunden")}</div>
                  <div className="mt-1 text-xs leading-relaxed text-muted-2">{t("Realistische Beispieldaten — jederzeit in den Einstellungen entfernbar.")}</div>
                </button>
                <button
                  onClick={() => setStartMode("empty")}
                  className={cn(
                    "cursor-pointer rounded-2xl border p-6 text-left transition-all",
                    startMode === "empty" ? "border-gold/50 bg-gold/10 shadow-[0_0_32px_-8px_rgba(212,175,55,0.5)]" : "border-white/10 hover:border-white/25"
                  )}
                >
                  <Database className={cn("h-6 w-6", startMode === "empty" ? "text-gold" : "text-muted-2")} strokeWidth={1.6} />
                  <div className={cn("mt-3 text-sm font-medium", startMode === "empty" ? "text-gold-bright" : "text-foreground")}>{t("Leer starten")}</div>
                  <div className="mt-1 text-xs leading-relaxed text-muted-2">{t("Direkt mit deinen echten Daten loslegen.")}</div>
                </button>
              </div>
              <div className="flex gap-3">
                <Button variant="outline" className="flex-1" onClick={() => setStep(1)} disabled={busy}>{t("Zurück")}</Button>
                <Button className="flex-1" onClick={finish} disabled={busy}>
                  {busy ? t("Einen Moment …") : t("Los geht's")}
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
