// src/routes/transactions/+page.svelte
<script lang="ts">
  import { Search, ArrowLeftRight } from "@lucide/svelte";
  import Card from "$lib/components/ui/Card.svelte";
  import Input from "$lib/components/ui/Input.svelte";
  import Select from "$lib/components/ui/Select.svelte";
  import Badge from "$lib/components/ui/Badge.svelte";
  import PageHeader from "$lib/components/ui/PageHeader.svelte";
  import EmptyState from "$lib/components/ui/EmptyState.svelte";
  import ManualAccounts from "$lib/components/ManualAccounts.svelte";
  import { CATEGORIES, CATEGORY_COLORS, CATEGORY_EMOJI } from "$lib/categorize";
  import { t } from "$lib/i18n";
  import { prefs } from "$lib/prefs.svelte";
  import { apiJson, cn, fmtEUR } from "$lib/utils";

  type Tx = {
    id: string;
    booking_date: string;
    amount: number;
    merchant: string | null;
    description: string | null;
    category: string;
    pending: number;
  };

  let txs = $state<Tx[]>([]);
  let months = $state<string[]>([]);
  let accounts = $state<Array<{ id: string; name: string; n: number }>>([]);
  let q = $state("");
  let category = $state("");
  let month = $state("");
  let account = $state("");
  let loading = $state(true);
  let editing = $state<string | null>(null);
  let reloadKey = $state(0);

  function load() {
    const params = new URLSearchParams();
    if (q) params.set("q", q);
    if (category) params.set("category", category);
    if (month) params.set("month", month);
    if (account) params.set("account", account);
    return apiJson<{ transactions: Tx[]; months: string[]; accounts: typeof accounts }>(`/api/transactions?${params}`)
      .then((d) => { txs = d.transactions; months = d.months; accounts = d.accounts; })
      .finally(() => (loading = false));
  }

  // Refetch on every filter change; typing is debounced so a search doesn't
  // fire a request per keystroke.
  $effect(() => {
    void [category, month, account, reloadKey];
    const query = q;
    const timer = setTimeout(load, query ? 250 : 0);
    return () => clearTimeout(timer);
  });

  async function setCat(id: string, cat: string) {
    txs = txs.map((tx) => (tx.id === id ? { ...tx, category: cat } : tx));
    editing = null;
    await fetch("/api/transactions", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, category: cat }),
    });
  }

  const spent = $derived(txs.filter((tx) => tx.amount < 0).reduce((s, tx) => s - tx.amount, 0));
  const earned = $derived(txs.filter((tx) => tx.amount > 0).reduce((s, tx) => s + tx.amount, 0));

  const fmtMonth = (m: string) => new Date(`${m}-01`).toLocaleDateString(prefs.locale, { month: "long", year: "numeric" });

  /** Bookings grouped by day, the way a bank statement reads. */
  const groups = $derived.by(() => {
    const out: Array<{ date: string; items: Tx[]; total: number }> = [];
    for (const tx of txs) {
      const last = out[out.length - 1];
      if (last && last.date === tx.booking_date) { last.items.push(tx); last.total += tx.amount; }
      else out.push({ date: tx.booking_date, items: [tx], total: tx.amount });
    }
    return out;
  });

  const dayLabel = (iso: string) => {
    const today = new Date().toISOString().slice(0, 10);
    const yesterday = new Date(Date.now() - 86400_000).toISOString().slice(0, 10);
    if (iso === today) return t("Heute");
    if (iso === yesterday) return t("Gestern");
    return new Date(iso).toLocaleDateString(prefs.locale, { weekday: "long", day: "numeric", month: "long", year: "numeric" });
  };

  const catOptions = $derived(CATEGORIES.map((c) => ({ value: c, label: `${CATEGORY_EMOJI[c] ?? ""} ${t(c)}` })));
</script>

<svelte:head><title>{t("Transaktionen")} · Achilles</title></svelte:head>

<div class="rise">
  <PageHeader title={t("Transaktionen")}>
    {#snippet actions()}
      <ManualAccounts onchange={() => reloadKey++} />
    {/snippet}
  </PageHeader>

  <div class="mb-5 grid grid-cols-3 gap-3">
    <Card class="px-4 py-3">
      <div class="text-xs text-muted">{t("Buchungen")}</div>
      <div class="num mt-0.5 text-lg font-semibold">{txs.length}</div>
    </Card>
    <Card class="px-4 py-3">
      <div class="text-xs text-muted">{t("Ausgaben")}</div>
      <div class="num mt-0.5 truncate text-lg font-semibold text-neg">−{fmtEUR(spent)}</div>
    </Card>
    <Card class="px-4 py-3">
      <div class="text-xs text-muted">{t("Einnahmen")}</div>
      <div class="num mt-0.5 truncate text-lg font-semibold text-pos">+{fmtEUR(earned)}</div>
    </Card>
  </div>

  <Card class="overflow-visible">
    <div class="flex flex-wrap gap-2.5 border-b border-line p-3">
      <div class="relative min-w-[220px] flex-1">
        <Search class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-faint" />
        <Input placeholder={t("Händler oder Beschreibung suchen …")} bind:value={q} class="pl-9" />
      </div>
      <Select bind:value={category} class="w-full sm:w-52" options={[{ value: "", label: t("Alle Kategorien") }, ...catOptions]} />
      <Select bind:value={month} class="w-full sm:w-48" options={[{ value: "", label: t("Alle Monate") }, ...months.map((m) => ({ value: m, label: fmtMonth(m) }))]} />
      <!-- Only from two accounts on: with one, the filter would be a choice without a choice. -->
      {#if accounts.length > 1}
        <Select bind:value={account} class="w-full sm:w-52" options={[{ value: "", label: t("Alle Konten") }, ...accounts.map((a) => ({ value: a.id, label: `${a.name} (${a.n})` }))]} />
      {/if}
    </div>

    {#if loading}
      <div class="space-y-3 p-5">
        {#each [0, 1, 2, 3, 4, 5] as i (i)}<div class="skeleton h-11"></div>{/each}
      </div>
    {:else if txs.length === 0}
      <EmptyState icon={ArrowLeftRight} title={t("Keine Transaktionen gefunden.")} />
    {:else}
      {#each groups as g (g.date)}
        <div class="flex items-center justify-between bg-surface-2 px-5 py-2 text-xs font-medium text-muted first:rounded-none">
          <span>{dayLabel(g.date)}</span>
          <span class={cn("num", g.total > 0 ? "text-pos" : "")}>{g.total > 0 ? "+" : ""}{fmtEUR(g.total)}</span>
        </div>
        <ul class="divide-y divide-line">
          {#each g.items as tx (tx.id)}
            <li class="flex items-center gap-3 px-5 py-3 transition-colors hover:bg-surface-2 sm:gap-4">
              <span
                class="flex size-9 shrink-0 items-center justify-center rounded-full text-base"
                style="background: color-mix(in srgb, {CATEGORY_COLORS[tx.category] ?? 'var(--faint)'} 14%, transparent)"
              >{CATEGORY_EMOJI[tx.category] ?? "•"}</span>
              <div class="min-w-0 flex-1">
                <div class="flex items-center gap-2">
                  <span class="truncate text-sm font-medium">{tx.merchant || tx.description || "—"}</span>
                  {#if tx.pending === 1}<Badge>{t("ausstehend")}</Badge>{/if}
                </div>
                {#if tx.merchant && tx.description}
                  <div class="truncate text-xs text-muted">{tx.description}</div>
                {/if}
              </div>
              <div class="hidden w-56 shrink-0 sm:block">
                {#if editing === tx.id}
                  <Select
                    size="sm"
                    autoOpen
                    value={tx.category}
                    options={catOptions}
                    onchange={(v) => setCat(tx.id, v)}
                    onclose={() => (editing = null)}
                  />
                {:else}
                  <button
                    type="button"
                    onclick={() => (editing = tx.id)}
                    class="flex h-8 w-full cursor-pointer items-center gap-1.5 rounded-lg px-2 text-left text-[13px] text-ink-2 transition-colors hover:bg-surface-3"
                    title={t("Kategorie ändern")}
                  >
                    <span class="size-2 shrink-0 rounded-full" style="background: {CATEGORY_COLORS[tx.category] ?? 'var(--faint)'}"></span>
                    <span class="truncate">{t(tx.category)}</span>
                  </button>
                {/if}
              </div>
              <span class={cn("num w-28 shrink-0 text-right text-sm font-semibold", tx.amount > 0 ? "text-pos" : "text-ink")}>
                {tx.amount > 0 ? "+" : ""}{fmtEUR(tx.amount)}
              </span>
            </li>
          {/each}
        </ul>
      {/each}
    {/if}
  </Card>
</div>

// src/app/transactions/page.tsx
"use client";

import { useCallback, useEffect, useState } from "react";
import { Search } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Input, Select } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { ManualAccounts } from "@/components/manual-accounts";
import { CATEGORIES, CATEGORY_COLORS } from "@/lib/categorize";
import { useI18n } from "@/lib/i18n";
import { apiJson, cn, fmtEUR, fmtDate } from "@/lib/utils";

type Tx = {
  id: string;
  booking_date: string;
  amount: number;
  merchant: string | null;
  description: string | null;
  category: string;
  pending: number;
};

export default function TransactionsPage() {
  const { t, lang } = useI18n();
  const [txs, setTxs] = useState<Tx[]>([]);
  const [months, setMonths] = useState<string[]>([]);
  const [accounts, setAccounts] = useState<Array<{ id: string; name: string; n: number }>>([]);
  const [q, setQ] = useState("");
  const [category, setCategory] = useState("");
  const [month, setMonth] = useState("");
  const [account, setAccount] = useState("");
  const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<string | null>(null);

  const load = useCallback(() => {
    const params = new URLSearchParams();
    if (q) params.set("q", q);
    if (category) params.set("category", category);
    if (month) params.set("month", month);
    if (account) params.set("account", account);
    apiJson<{ transactions: Tx[]; months: string[]; accounts: typeof accounts }>(`/api/transactions?${params}`)
      .then((d) => { setTxs(d.transactions); setMonths(d.months); setAccounts(d.accounts); })
      .finally(() => setLoading(false));
  }, [q, category, month, account]);

  useEffect(() => {
    const timer = setTimeout(load, q ? 250 : 0);
    return () => clearTimeout(timer);
  }, [load, q]);

  const setCat = async (id: string, cat: string) => {
    setTxs((prev) => prev.map((tx) => (tx.id === id ? { ...tx, category: cat } : tx)));
    setEditing(null);
    await fetch("/api/transactions", {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ id, category: cat }),
    });
  };

  const spent = txs.filter((tx) => tx.amount < 0).reduce((s, tx) => s - tx.amount, 0);
  const earned = txs.filter((tx) => tx.amount > 0).reduce((s, tx) => s + tx.amount, 0);

  const fmtMonth = (m: string) =>
    new Date(`${m}-01`).toLocaleDateString(lang === "de" ? "de-DE" : "en-US", { month: "long", year: "numeric" });

  return (
    <div className="space-y-6">
      <div className="rise flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="font-display text-4xl gold-text">{t("Transaktionen")}</h1>
          <p className="mt-1 text-sm text-muted-2">
            {t("{n} Buchungen", { n: txs.length })} · <span className="text-rose-soft">−{fmtEUR(spent)}</span> · <span className="text-emerald-soft">+{fmtEUR(earned)}</span>
          </p>
        </div>
        <ManualAccounts onChange={load} />
      </div>

      <Card className="rise rise-1 p-4">
        <div className="flex flex-wrap gap-3">
          <div className="relative min-w-[220px] flex-1">
            <Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-2" />
            <Input placeholder={t("Händler oder Beschreibung suchen …")} value={q} onChange={(e) => setQ(e.target.value)} className="pl-10" />
          </div>
          <Select value={category} onChange={(e) => setCategory(e.target.value)} className="w-full sm:w-56">
            <option value="">{t("Alle Kategorien")}</option>
            {CATEGORIES.map((c) => <option key={c} value={c}>{t(c)}</option>)}
          </Select>
          <Select value={month} onChange={(e) => setMonth(e.target.value)} className="w-full sm:w-52">
            <option value="">{t("Alle Monate")}</option>
            {months.map((m) => <option key={m} value={m}>{fmtMonth(m)}</option>)}
          </Select>
          {/* Erst ab zwei Konten: Bei nur einem wäre der Filter ein Auswahlfeld
              ohne Auswahl. */}
          {accounts.length > 1 && (
            <Select value={account} onChange={(e) => setAccount(e.target.value)} className="w-full sm:w-56">
              <option value="">{t("Alle Konten")}</option>
              {accounts.map((a) => (
                <option key={a.id} value={a.id}>{a.name} ({a.n})</option>
              ))}
            </Select>
          )}
        </div>
      </Card>

      <Card className="rise rise-2 overflow-hidden">
        {loading ? (
          <div className="p-12 text-center text-sm text-muted-2 animate-pulse">{t("Lade Transaktionen …")}</div>
        ) : txs.length === 0 ? (
          <div className="p-12 text-center text-sm text-muted-2">{t("Keine Transaktionen gefunden.")}</div>
        ) : (
          <div className="divide-y divide-white/[0.05]">
            {txs.map((tx) => (
              <div key={tx.id} className="flex items-center gap-4 px-5 py-3.5 transition-colors hover:bg-white/[0.03]">
                <div
                  className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-sm font-semibold"
                  style={{
                    background: `${CATEGORY_COLORS[tx.category] ?? "#6b7280"}14`,
                    color: CATEGORY_COLORS[tx.category] ?? "#6b7280",
                    border: `1px solid ${CATEGORY_COLORS[tx.category] ?? "#6b7280"}25`,
                  }}
                >
                  {(tx.merchant || tx.description || "?").charAt(0).toUpperCase()}
                </div>
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2">
                    <span className="truncate text-sm font-medium">{tx.merchant || tx.description || "—"}</span>
                    {tx.pending === 1 && <Badge color="#94a3b8">{t("ausstehend")}</Badge>}
                  </div>
                  <div className="mt-0.5 truncate text-xs text-muted-2">
                    {fmtDate(tx.booking_date)}{tx.merchant && tx.description ? ` · ${tx.description}` : ""}
                  </div>
                </div>
                <div className="shrink-0">
                  {editing === tx.id ? (
                    <Select
                      autoFocus
                      value={tx.category}
                      onChange={(e) => setCat(tx.id, e.target.value)}
                      onBlur={() => setEditing(null)}
                      className="h-8 w-52 text-xs"
                    >
                      {CATEGORIES.map((c) => <option key={c} value={c}>{t(c)}</option>)}
                    </Select>
                  ) : (
                    <button onClick={() => setEditing(tx.id)} className="cursor-pointer" title={t("Kategorie ändern")}>
                      <Badge color={CATEGORY_COLORS[tx.category] ?? "#6b7280"}>{t(tx.category)}</Badge>
                    </button>
                  )}
                </div>
                <span className={cn("num w-28 shrink-0 text-right text-sm font-semibold", tx.amount > 0 ? "text-emerald-soft" : "text-foreground")}>
                  {tx.amount > 0 ? "+" : ""}{fmtEUR(tx.amount)}
                </span>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
