// src/components/app-shell.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { LayoutDashboard, ArrowLeftRight, Gem, TrendingUp, Eye, QrCode, Settings, Shield, ShieldCheck, Flame, PiggyBank, HandCoins, Home, Briefcase } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { apiJson, cn } from "@/lib/utils";

const NAV = [
  { href: "/", label: "Übersicht", icon: LayoutDashboard },
  { href: "/transactions", label: "Transaktionen", icon: ArrowLeftRight },
  { href: "/metals", label: "Edelmetalle", icon: Gem },
  { href: "/investments", label: "Investments", icon: TrendingUp },
  { href: "/watchlist", label: "Watchlist", icon: Eye },
  { href: "/pension", label: "Vorsorge", icon: PiggyBank },
  { href: "/emergency", label: "Notgroschen", icon: ShieldCheck },
  { href: "/loans", label: "Kredite", icon: HandCoins },
  { href: "/realestate", label: "Immobilien", icon: Home },
  { href: "/business", label: "Unternehmenswert", icon: Briefcase },
  { href: "/fire", label: "FIRE", icon: Flame },
  { href: "/connect", label: "Verbinden", icon: QrCode },
];

/**
 * Sits apart from the list above: settings is not a place you go to look at
 * something, it is where you go to change something — and it is where the
 * update notice belongs.
 */
const SETTINGS = { href: "/settings", label: "Einstellungen", icon: Settings };

/** Seiten, die statt der Lesebreite die ganze Fensterbreite bekommen. */
const FULL_WIDTH = new Set(["/watchlist"]);

export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const router = useRouter();
  const { t } = useI18n();
  const [checked, setChecked] = useState(false);
  const [updateAvailable, setUpdateAvailable] = useState(false);

  // Ersteinrichtung: ohne abgeschlossenes Setup zum Wizard umleiten.
  //
  // Auf der Login-Seite darf das nicht laufen: /api/settings ist geschützt,
  // liefert dort also 401. Der Setup-Stand ist damit unbekannt — und die
  // Antwort ohne setupDone sähe aus wie „Setup fehlt“ und würde zum Wizard
  // schicken, den die Middleware sofort wieder auf /login zurückwirft.
  // Wer sich anmelden will, hat das Setup ohnehin hinter sich.
  useEffect(() => {
    if (pathname === "/login") { setChecked(true); return; }
    apiJson<{ setupDone: boolean }>("/api/settings")
      .then((s) => {
        if (!s.setupDone && pathname !== "/setup") router.replace("/setup");
        else setChecked(true);
      })
      .catch(() => setChecked(true));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pathname]);

  /*
   * Once per page load, not per navigation: the shell survives client-side
   * route changes, and the release lookup goes out to GitHub. The server caches
   * it for ten minutes anyway, but there is no reason to ask again just because
   * someone clicked a link.
   *
   * Only `true` shows the badge — the endpoint reports null when it could not
   * check, and an unknown state must not be dressed up as a pending update.
   */
  useEffect(() => {
    if (pathname === "/login" || pathname === "/setup") return;
    apiJson<{ updateAvailable: boolean | null }>("/api/update")
      .then((u) => setUpdateAvailable(u.updateAvailable === true))
      .catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (pathname === "/setup" || pathname === "/login") {
    return (
      <div className="min-h-screen">
        <div className="aurora" />
        {children}
      </div>
    );
  }

  return (
    <div className="flex min-h-screen">
      <div className="aurora" />

      {/* Sidebar */}
      <aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col p-4 lg:flex">
        <div className="glass flex h-full flex-col rounded-glass p-5">
          <Link href="/" className="flex items-center gap-3 px-2 pb-6">
            <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-[#e9cd6f] to-[#9a7a26] shadow-[0_8px_20px_-6px_rgba(212,175,55,0.55)]">
              <Shield className="h-5 w-5 text-[#1a1405]" strokeWidth={2.2} />
            </div>
            <div>
              <div className="font-display text-lg leading-tight tracking-wide gold-text">Achilles</div>
              <div className="text-[10px] uppercase tracking-[0.22em] text-muted-2">Financials</div>
            </div>
          </Link>

          <div className="hairline mb-4" />

          <nav className="flex flex-1 flex-col gap-1">
            {NAV.map(({ href, label, icon: Icon }) => {
              const active = pathname === href;
              return (
                <Link
                  key={href}
                  href={href}
                  className={cn(
                    "group flex items-center gap-3 rounded-xl px-3.5 py-2.5 text-sm transition-all duration-200",
                    active
                      ? "bg-gradient-to-r from-gold/15 to-transparent text-gold-bright border border-gold/20 shadow-[0_0_24px_-8px_rgba(212,175,55,0.4)]"
                      : "text-muted hover:text-foreground hover:bg-white/[0.05] border border-transparent"
                  )}
                >
                  <Icon className={cn("h-[18px] w-[18px] transition-colors", active ? "text-gold" : "text-muted-2 group-hover:text-foreground")} strokeWidth={1.8} />
                  {t(label)}
                </Link>
              );
            })}
          </nav>

          <div className="hairline my-4" />

          <Link
            href={SETTINGS.href}
            className={cn(
              "group flex items-center gap-3 rounded-xl px-3.5 py-2.5 text-sm transition-all duration-200",
              pathname === SETTINGS.href
                ? "bg-gradient-to-r from-gold/15 to-transparent text-gold-bright border border-gold/20 shadow-[0_0_24px_-8px_rgba(212,175,55,0.4)]"
                : "text-muted hover:text-foreground hover:bg-white/[0.05] border border-transparent"
            )}
          >
            <SETTINGS.icon
              className={cn("h-[18px] w-[18px] transition-colors", pathname === SETTINGS.href ? "text-gold" : "text-muted-2 group-hover:text-foreground")}
              strokeWidth={1.8}
            />
            {t(SETTINGS.label)}
            {updateAvailable && (
              <span
                className="ml-auto flex h-5 min-w-5 items-center justify-center rounded-full bg-gold px-1.5 text-[11px] font-semibold text-[#1a1405] shadow-[0_0_12px_-2px_rgba(212,175,55,0.8)]"
                title={t("Ein Update ist verfügbar")}
              >
                1
              </span>
            )}
          </Link>

          <div className="hairline my-4" />
          <div className="px-2 text-[10px] leading-relaxed text-muted-2">
            Private Wealth Dashboard
            <br />
            Self-hosted · Proxmox
          </div>
        </div>
      </aside>

      {/* Mobile top nav */}
      <div className="fixed inset-x-0 top-0 z-40 p-3 lg:hidden">
        <div className="glass flex items-center gap-1 overflow-x-auto rounded-2xl p-2">
          {[...NAV, SETTINGS].map(({ href, label, icon: Icon }) => {
            const active = pathname === href;
            return (
              <Link
                key={href}
                href={href}
                className={cn(
                  "relative flex shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-xs",
                  active ? "bg-gold/15 text-gold-bright" : "text-muted"
                )}
              >
                <Icon className="h-4 w-4" strokeWidth={1.8} />
                <span className="hidden sm:inline">{t(label)}</span>
                {href === SETTINGS.href && updateAvailable && (
                  // Overlaid rather than inline: the labels are hidden on narrow
                  // screens, so a badge in the flow would sit next to nothing.
                  <span className="absolute -right-0.5 -top-0.5 flex h-4 min-w-4 items-center justify-center rounded-full bg-gold px-1 text-[10px] font-semibold text-[#1a1405]">
                    1
                  </span>
                )}
              </Link>
            );
          })}
        </div>
      </div>

      <main className="min-w-0 flex-1 px-4 pb-16 pt-20 sm:px-6 lg:ml-64 lg:px-10 lg:pt-8">
        {/* 1400px sind eine Lesebreite — sinnvoll für Tabellen und Text.
            Ein Kachelraster gewinnt dagegen mit jeder Spalte, die draufpasst,
            und darf die volle Fensterbreite nutzen. */}
        <div className={cn("mx-auto", FULL_WIDTH.has(pathname) ? "max-w-none" : "max-w-[1400px]", !checked && "opacity-0")}>
          {children}
        </div>
      </main>
    </div>
  );
}

// src/lib/components/AppShell.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { onMount } from "svelte";
  import { page } from "$app/state";
  import { afterNavigate } from "$app/navigation";
  import {
    LayoutDashboard, ArrowLeftRight, Gem, TrendingUp, Eye, QrCode, Settings, Shield, ShieldCheck, Flame,
    PiggyBank, HandCoins, Home, Briefcase, Menu, X, LogOut, Sun, Moon, Monitor,
  } from "@lucide/svelte";
  import { t } from "$lib/i18n";
  import { apiJson, cn } from "$lib/utils";
  import { prefs, setTheme, type Theme } from "$lib/prefs.svelte";

  let { authEnabled = false, children }: { authEnabled?: boolean; children: Snippet } = $props();

  const GROUPS = [
    {
      label: null,
      items: [
        { href: "/", label: "Übersicht", icon: LayoutDashboard },
        { href: "/transactions", label: "Transaktionen", icon: ArrowLeftRight },
      ],
    },
    {
      label: "Vermögen",
      items: [
        { href: "/investments", label: "Investments", icon: TrendingUp },
        { href: "/watchlist", label: "Watchlist", icon: Eye },
        { href: "/metals", label: "Edelmetalle", icon: Gem },
        { href: "/pension", label: "Vorsorge", icon: PiggyBank },
        { href: "/realestate", label: "Immobilien", icon: Home },
        { href: "/business", label: "Unternehmenswert", icon: Briefcase },
        { href: "/loans", label: "Kredite", icon: HandCoins },
      ],
    },
    {
      label: "Planung",
      items: [
        { href: "/emergency", label: "Notgroschen", icon: ShieldCheck },
        { href: "/fire", label: "FIRE", icon: Flame },
      ],
    },
  ];

  /**
   * Sits apart from the lists above: these are not places you go to look at
   * something, they are where you go to change something — and settings is
   * where the update notice belongs.
   */
  const FOOT = [
    { href: "/connect", label: "Verbinden", icon: QrCode },
    { href: "/settings", label: "Einstellungen", icon: Settings },
  ];

  /** Bottom tabs on phones — the four places you open most, plus the drawer. */
  const TABS = [
    { href: "/", label: "Übersicht", icon: LayoutDashboard },
    { href: "/transactions", label: "Transaktionen", icon: ArrowLeftRight },
    { href: "/investments", label: "Investments", icon: TrendingUp },
    { href: "/fire", label: "FIRE", icon: Flame },
  ];

  /** Pages that get the full window width instead of the reading width. */
  const FULL_WIDTH = new Set(["/watchlist"]);

  let drawer = $state(false);
  let updateAvailable = $state(false);

  const path = $derived(page.url.pathname);
  const isActive = (href: string) => (href === "/" ? path === "/" : path === href || path.startsWith(href + "/"));

  afterNavigate(() => (drawer = false));

  /*
   * Once per page load, not per navigation: the shell survives client-side
   * route changes, and the release lookup goes out to GitHub. Only `true` shows
   * the badge — null means "could not check", which must not look like an update.
   */
  onMount(() => {
    apiJson<{ updateAvailable: boolean | null }>("/api/update")
      .then((u) => (updateAvailable = u.updateAvailable === true))
      .catch(() => {});
  });

  async function logout() {
    await fetch("/api/auth/logout", { method: "POST" });
    window.location.href = "/login";
  }

  const THEMES: Array<{ value: Theme; icon: typeof Sun; label: string }> = [
    { value: "light", icon: Sun, label: "Hell" },
    { value: "dark", icon: Moon, label: "Dunkel" },
    { value: "system", icon: Monitor, label: "System" },
  ];
</script>

{#snippet navLink(item: { href: string; label: string; icon: typeof Sun }, badge = false)}
  {@const active = isActive(item.href)}
  <a
    href={item.href}
    aria-current={active ? "page" : undefined}
    class={cn(
      "group flex items-center gap-3 rounded-xl px-3 py-2 text-[14px] font-medium transition-colors",
      active ? "bg-accent-soft text-accent" : "text-ink-2 hover:bg-surface-3 hover:text-ink"
    )}
  >
    <item.icon class={cn("size-[18px] shrink-0", active ? "text-accent" : "text-muted group-hover:text-ink")} strokeWidth={1.9} />
    <span class="truncate">{t(item.label)}</span>
    {#if badge}
      <span
        class="ml-auto flex h-5 min-w-5 items-center justify-center rounded-full bg-accent px-1.5 text-[11px] font-semibold text-accent-ink"
        title={t("Ein Update ist verfügbar")}>1</span
      >
    {/if}
  </a>
{/snippet}

{#snippet sidebar()}
  <div class="flex h-full flex-col">
    <a href="/" class="flex items-center gap-2.5 px-5 pt-5 pb-4">
      <span class="flex size-8.5 items-center justify-center rounded-[10px] bg-accent text-accent-ink shadow-sm">
        <Shield class="size-[18px]" strokeWidth={2.3} />
      </span>
      <span class="leading-tight">
        <span class="block text-[15px] font-semibold tracking-tight text-ink">Achilles</span>
        <span class="block text-[11px] font-medium text-muted">Financials</span>
      </span>
    </a>

    <nav class="flex-1 space-y-5 overflow-y-auto px-3 py-2">
      {#each GROUPS as g (g.label)}
        <div class="space-y-0.5">
          {#if g.label}
            <div class="px-3 pb-1 text-[11px] font-semibold uppercase tracking-wider text-faint">{t(g.label)}</div>
          {/if}
          {#each g.items as item (item.href)}
            {@render navLink(item)}
          {/each}
        </div>
      {/each}
    </nav>

    <div class="space-y-0.5 border-t border-line px-3 py-3">
      {#each FOOT as item (item.href)}
        {@render navLink(item, item.href === "/settings" && updateAvailable)}
      {/each}
      {#if authEnabled}
        <button
          type="button"
          onclick={logout}
          class="group flex w-full cursor-pointer items-center gap-3 rounded-xl px-3 py-2 text-[14px] font-medium text-ink-2 transition-colors hover:bg-surface-3 hover:text-ink"
        >
          <LogOut class="size-[18px] text-muted group-hover:text-ink" strokeWidth={1.9} />
          {t("Abmelden")}
        </button>
      {/if}
    </div>

    <div class="flex items-center justify-between gap-2 border-t border-line px-5 py-3">
      <span class="text-[11px] text-faint">{t("Darstellung")}</span>
      <div class="flex gap-0.5 rounded-lg bg-surface-3 p-0.5">
        {#each THEMES as th (th.value)}
          <button
            type="button"
            title={t(th.label)}
            aria-label={t(th.label)}
            aria-pressed={prefs.theme === th.value}
            onclick={() => setTheme(th.value)}
            class={cn(
              "flex size-6.5 cursor-pointer items-center justify-center rounded-md transition-colors",
              prefs.theme === th.value ? "bg-surface text-ink shadow-[var(--shadow-card)]" : "text-faint hover:text-ink"
            )}
          >
            <th.icon class="size-3.5" />
          </button>
        {/each}
      </div>
    </div>
  </div>
{/snippet}

<div class="min-h-screen lg:pl-[248px]">
  <!-- Desktop sidebar -->
  <aside class="fixed inset-y-0 left-0 z-40 hidden w-[248px] border-r border-line bg-surface lg:block">
    {@render sidebar()}
  </aside>

  <!-- Mobile top bar -->
  <div class="sticky top-0 z-40 flex h-14 items-center justify-between border-b border-line bg-surface/90 px-4 backdrop-blur-md lg:hidden" style="padding-top: env(safe-area-inset-top)">
    <a href="/" class="flex items-center gap-2">
      <span class="flex size-7.5 items-center justify-center rounded-lg bg-accent text-accent-ink">
        <Shield class="size-4" strokeWidth={2.3} />
      </span>
      <span class="text-[15px] font-semibold tracking-tight">Achilles</span>
    </a>
    <button
      type="button"
      class="relative -mr-2 rounded-lg p-2 text-ink-2 hover:bg-surface-3"
      onclick={() => (drawer = true)}
      aria-label={t("Menü öffnen")}
    >
      <Menu class="size-5" />
      {#if updateAvailable}<span class="absolute right-1.5 top-1.5 size-2 rounded-full bg-accent"></span>{/if}
    </button>
  </div>

  <!-- Mobile drawer -->
  {#if drawer}
    <div class="fixed inset-0 z-50 lg:hidden">
      <button type="button" class="absolute inset-0 bg-[rgb(15_20_30/0.45)]" aria-label={t("Menü schließen")} onclick={() => (drawer = false)}></button>
      <aside class="rise absolute inset-y-0 left-0 w-[280px] max-w-[85vw] border-r border-line bg-surface shadow-[var(--shadow-pop)]">
        <button
          type="button"
          class="absolute right-3 top-4 rounded-lg p-1.5 text-muted hover:bg-surface-3"
          onclick={() => (drawer = false)}
          aria-label={t("Menü schließen")}
        >
          <X class="size-4.5" />
        </button>
        {@render sidebar()}
      </aside>
    </div>
  {/if}

  <main class="min-w-0 px-4 pt-6 pb-28 sm:px-6 lg:px-10 lg:pt-9 lg:pb-14">
    <!-- 1280px is a reading width — right for tables and text. A tile grid gains
         with every column that fits and may use the whole window. -->
    <div class={cn("mx-auto", FULL_WIDTH.has(path) ? "max-w-none" : "max-w-[1280px]")}>
      {@render children()}
    </div>
  </main>

  <!-- Mobile bottom tabs -->
  <nav class="fixed inset-x-0 bottom-0 z-40 grid grid-cols-5 border-t border-line bg-surface/95 backdrop-blur-md lg:hidden" style="padding-bottom: env(safe-area-inset-bottom)">
    {#each TABS as tab (tab.href)}
      {@const active = isActive(tab.href)}
      <a href={tab.href} class={cn("flex flex-col items-center gap-0.5 py-2 text-[10px] font-medium", active ? "text-accent" : "text-muted")}>
        <tab.icon class="size-5" strokeWidth={active ? 2.2 : 1.8} />
        <span class="max-w-full truncate px-1">{t(tab.label)}</span>
      </a>
    {/each}
    <button type="button" onclick={() => (drawer = true)} class="relative flex flex-col items-center gap-0.5 py-2 text-[10px] font-medium text-muted">
      <Menu class="size-5" strokeWidth={1.8} />
      <span>{t("Mehr")}</span>
      {#if updateAvailable}<span class="absolute right-[30%] top-1.5 size-2 rounded-full bg-accent"></span>{/if}
    </button>
  </nav>
</div>
