// src/lib/components/ui/Button.svelte
<script lang="ts" module>
  export type ButtonVariant = "primary" | "secondary" | "ghost" | "outline" | "danger" | "soft";
  export type ButtonSize = "sm" | "md" | "lg" | "icon" | "icon-sm";

  const BASE =
    "inline-flex items-center justify-center gap-2 whitespace-nowrap font-medium transition-colors duration-150 select-none cursor-pointer disabled:pointer-events-none disabled:opacity-45 [&_svg]:shrink-0";

  const VARIANTS: Record<ButtonVariant, string> = {
    primary: "bg-accent text-accent-ink hover:brightness-105 active:brightness-95 shadow-sm",
    secondary: "bg-surface text-ink border border-line hover:bg-surface-2 hover:border-line-strong shadow-[var(--shadow-card)]",
    outline: "border border-line text-ink hover:bg-surface-2",
    ghost: "text-ink-2 hover:bg-surface-3 hover:text-ink",
    soft: "bg-accent-soft text-accent hover:brightness-[0.98]",
    danger: "border border-neg/30 text-neg hover:bg-neg-soft",
  };

  const SIZES: Record<ButtonSize, string> = {
    sm: "h-8 px-3 text-[13px] rounded-lg [&_svg]:size-3.5",
    md: "h-9.5 px-4 text-sm rounded-xl [&_svg]:size-4",
    lg: "h-11 px-6 text-[15px] rounded-xl [&_svg]:size-4.5",
    icon: "size-9 rounded-xl [&_svg]:size-4",
    "icon-sm": "size-7.5 rounded-lg [&_svg]:size-3.5",
  };

  export function buttonClass(variant: ButtonVariant = "primary", size: ButtonSize = "md") {
    return `${BASE} ${VARIANTS[variant]} ${SIZES[size]}`;
  }
</script>

<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLButtonAttributes } from "svelte/elements";
  import { cn } from "$lib/utils";

  let {
    variant = "primary",
    size = "md",
    href,
    target,
    class: klass = "",
    children,
    ...rest
  }: HTMLButtonAttributes & {
    variant?: ButtonVariant;
    size?: ButtonSize;
    href?: string;
    target?: string;
    children?: Snippet;
  } = $props();
</script>

{#if href}
  <a {href} {target} rel={target === "_blank" ? "noopener noreferrer" : undefined} class={cn(buttonClass(variant, size), klass)}>
    {@render children?.()}
  </a>
{:else}
  <button type="button" class={cn(buttonClass(variant, size), klass)} {...rest}>
    {@render children?.()}
  </button>
{/if}

// src/components/ui/button.tsx
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl text-sm font-medium transition-all duration-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-gold/50 disabled:pointer-events-none disabled:opacity-40 cursor-pointer select-none",
  {
    variants: {
      variant: {
        default:
          "bg-gradient-to-b from-[#e9cd6f] via-[#d4af37] to-[#b8912e] text-[#1a1405] font-semibold shadow-[0_8px_24px_-8px_rgba(212,175,55,0.5),0_1px_0_rgba(255,255,255,0.4)_inset] hover:brightness-110 hover:shadow-[0_12px_32px_-8px_rgba(212,175,55,0.65)] active:scale-[0.98]",
        glass:
          "glass text-foreground hover:border-white/20 hover:bg-white/[0.07] active:scale-[0.98]",
        ghost: "text-muted hover:text-foreground hover:bg-white/[0.06] active:scale-[0.98]",
        outline:
          "border border-white/12 text-foreground hover:bg-white/[0.05] hover:border-white/20 active:scale-[0.98]",
        destructive:
          "border border-rose-soft/30 text-rose-soft hover:bg-rose-soft/10 active:scale-[0.98]",
      },
      size: {
        default: "h-10 px-5",
        sm: "h-8 px-3 text-xs rounded-lg",
        lg: "h-12 px-7 text-base rounded-2xl",
        icon: "h-9 w-9 rounded-lg",
      },
    },
    defaultVariants: { variant: "default", size: "default" },
  }
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, ...props }, ref) => (
    <button ref={ref} className={cn(buttonVariants({ variant, size }), className)} {...props} />
  )
);
Button.displayName = "Button";

export { Button, buttonVariants };
